### ISSUE TITLE
why watchman as a dependency?

### ISSUE THREAD

**Issue by laoshaw** [yaegassy/coc-volar#105]
really heavy application, takes a long time to install on linux(along with boost c++ libraries etc), can we use some better alternatives

**Comment by yaegassy** [comment]
`watchman` is used by coc.nvim to detect the addition of new files and to generate events for the language server to recognize new files.

This is a specification of "coc.nvim".

If you have difficulty installing `watchman`, you can use `coc-volar` without `watchman`, but you may not be able to immediately use "volar's IntelliSense" with the newly added files.

In this case, please execute the command to restart the language server.

- `:CocCommand volar.action.restartServer`
- `:CocRestart`

---

Changed watchman documentation from "required" to "recommended" in README.
