### ISSUE TITLE
Since @volar/server v0.30.2, completion is broken by `-` such as `v-`

### ISSUE THREAD

**Issue by yaegassy** [yaegassy/coc-volar#110]
## Description

I think this problem is probably coming from this commit. <https://github.com/johnsoncodehk/volar/commit/097cfd0430e9b7efce9a64cef7645c14356678dd#diff-4687ed2e9ff82d7e4c306953ce08ad1136d7bc1a89f4d21e6215727f730b30d5>

No problem for VSCode's volar extension.

### [NG] @volar/server v0.30.2 later

https://user-images.githubusercontent.com/188642/150523907-f04e5fbc-98ad-4711-8aaf-006108d3b817.mp4

### [OK] @volar/server v0.30.1

https://user-images.githubusercontent.com/188642/150523970-f9f120d4-6146-4bc3-a6f8-e23204dd6f22.mp4

**Comment by yaegassy** [comment]
There is a way to force completion refresh in coc-volar's completion middleware when `context.triggerCharacter` is `-`...

```typescript
if (context.triggerCharacter === '-') {
  // force completion
  await workspace.nvim.call('coc#start');
}
```

**Comment by johnsoncodehk** [comment]
Hi @yaegassy, I have an assumption is that volar add `-` to css completion trigger character in https://github.com/johnsoncodehk/volar/commit/cd054262567f51cc16296dc1a0008097ec5d459c, this leads to when user input `-` of `v-if`, coc trigger the second time auto-complete request. But `-` is a invalid trigger character for html completion, so volar just ignore html completion in the second time auto-complete.

To confirm this, could you check how many times would coc send auto-complete request to language server when input `v` and `-`? In vscode it just send one times.

**Comment by yaegassy** [comment]
@johnsoncodehk 

> Hi @yaegassy, I have an assumption is that volar add - to css completion trigger character in johnsoncodehk/volar@cd05426, this leads to when user input - of v-if, coc trigger the second time auto-complete request. But - is a invalid trigger character for html completion, so volar just ignore html completion in the second time auto-complete.

I changed the trigger character in the css to the previous one and tried it.

```
css: ['.', '@', '/'/* path completion */],
```

Indeed, the html completion problem has been solved!!!!

---

> To confirm this, could you check how many times would coc send auto-complete request to language server when input v and -? In vscode it just send one times.

I'm not sure if my method of checking is correct, but I can confirm that textDocument/completion is being sent when I type `-`. Perhaps this will be the second time.

```
[Trace - 19:02:33] Sending request 'textDocument/completion - (9)'.
Params: {
    "textDocument": {
        "uri": "file:///Users/yaegassy/sandbox/check-volar-vite-ts/src/App.vue"
    },
    "position": {
        "line": 17,
        "character": 7
    },
    "context": {
        "triggerKind": 2,
        "triggerCharacter": "-"
    }
}

[Trace - 19:02:33] Received response 'textDocument/completion - (9)' in 3ms.
Result: {
    "isIncomplete": false,
    "items": []
}
```

**Comment by johnsoncodehk** [comment]
I think this is coc issue, when language server response completion list with `"isIncomplet": false` and previous completion list is not close yet, language client should not trigger a new auto-complete request.

**Comment by yaegassy** [comment]
Sorry for the late reply. I will try to sort out the problem and report the issue to `coc.nvim`.

**Comment by yaegassy** [comment]
A fix on the `coc.nvim` side solved this problem. <https://github.com/neoclide/coc.nvim/commit/213534b86a96267b0d33a19e65d0bdd7bf9dc521>
