### ISSUE TITLE
Auto import has a bug

### ISSUE THREAD

**Issue by lixiao189** [yaegassy/coc-volar#134]
When I auto import some function from vue, for example the onMounted function, this plugin cause some problem.

![image.png](https://s2.loli.net/2022/03/27/JdrqshFYubeMjUG.png)

It prompts that `[coc.nvim]Error on applyEdits:file:///[My file address changed] before apply edit`

**Comment by yaegassy** [comment]
If the problem is an error when using auto-import from "CodeAction", it may be similar to another issue. <https://github.com/yaegassy/coc-volar/issues/112 >

Try workaround.

- <https://github.com/yaegassy/coc-volar/issues/112#issuecomment-1026421223>

**Comment by yaegassy** [comment]
Thanks for the additional info. 🙇

This problem was reproduced outside of takeover mode. It is also reproduced when using LSP client plug-ins other than coc.nvim.

I think this is probably a problem that needs to be adjusted on the Language Server side of upstream, but since this problem cannot be reproduced correctly in VSCode, we are taking a look at the situation.

**Comment by lixiao189** [comment]
Thank you

**Comment by yaegassy** [comment]
**MEMO**:

- <https://github.com/neoclide/coc.nvim/blob/master/src/core/files.ts#L438-L444>

```typescript
        if (typeof version === 'number' && version > 0) {
          let doc = documents.getDocument(uri)
          if (!doc) throw new Error(`${uri} not loaded`)
          if (doc.version != version) {
            throw new Error(`${uri} changed before apply edit`)
          }
        }
```

**Comment by yaegassy** [comment]
This may be a related issue. https://github.com/johnsoncodehk/volar/issues/1113

**Comment by lixiao189** [comment]
> This may be a related issue. [johnsoncodehk/volar#1113](https://github.com/johnsoncodehk/volar/issues/1113)

Thank you

**Comment by yaegassy** [comment]
I reported the issue to coc.nvim.

**Comment by lixiao189** [comment]
Thank you
