### ISSUE TITLE
no autocomplete for js or ts code in vue3 file

### ISSUE THREAD

**Issue by laoshaw** [yaegassy/coc-volar#135]
in the script section of my vue code, it seems there is no autocompete for any javascript or typescript code, is this supposed to work?

tried volar in vscode all autocomplete with javascript and typescript worked fine.

**Comment by yaegassy** [comment]
It works fine in my environment.

https://user-images.githubusercontent.com/188642/160662056-54e8dfa1-c541-47d5-a55d-a469208fa5a8.mp4

**Comment by laoshaw** [comment]
can you do:

```
const str="string";
str.<TAB>
```

and it brings up all the string methods for example? <TAB> could be whatever your settings for the autocomplete?

vscode/volar will bringup all methods for str in SFC, vim/volar could not, for me at least

I installed both coc and Plug for volar, it's unclear if I need both from coc-volar's README so I just loaded both

Thanks,

**Comment by yaegassy** [comment]
Of course, it works fine.

<img width="335" alt="coc-volar-issue135-2" src="https://user-images.githubusercontent.com/188642/160663974-19752844-4add-4415-beb2-3ed03378c5ca.png">

**Comment by laoshaw** [comment]
Then something must be wrong on my side. I'm using options-api but I don't think that will make a difference. Will debug.

**Comment by yaegassy** [comment]
Try using `defineComponent`.

```vue
<script lang="ts">
import { defineComponent } from "vue";

export default defineComponent({
  //
});
</script>
```

**Comment by laoshaw** [comment]
yeah I use that by default, did not help
