### ISSUE TITLE
Auto complete don't work with Component props

### ISSUE THREAD

**Issue by Aaron34R** [yaegassy/coc-volar#136]
![image](https://user-images.githubusercontent.com/56248683/161370668-9dbd083e-e20f-49ab-9654-d5b3707db043.png)
i can't use autocomplete width component props like the document does

**Comment by yaegassy** [comment]
I cannot reproduce this in my environment. It works fine.

<img width="599" alt="coc-volar-issue-136-1" src="https://user-images.githubusercontent.com/188642/161371206-39ccbee6-0f9e-42fc-9a4b-ba786ce4a8a2.png">

**Comment by Aaron34R** [comment]
> Do i need to set anything before it

**Comment by Aaron34R** [comment]
> I cannot reproduce this in my environment. It works fine.
> 
> <img alt="coc-volar-issue-136-1" width="599" src="https://user-images.githubusercontent.com/188642/161371206-39ccbee6-0f9e-42fc-9a4b-ba786ce4a8a2.png">

Do i need to set anything before it

**Comment by yaegassy** [comment]
I don't think you need to do any special setup. Maybe there is something wrong with your project.

Create a project with `create-vite` or `create-vue` and try to see if it works correctly.

**create-vite**:

> https://github.com/vitejs/vite/tree/main/packages/create-vite

```
yarn create vite example-proj --template vue-ts
```

**create-vue**:

> https://github.com/vuejs/create-vue

```
npm init vue@3
```

In coc-volar, this can be enabled by executing the following `CocCommand`.

```
:CocCommand volar.initializeTakeOverMode
```

For more information, please check here. <https://github.com/yaegassy/coc-volar#how-to-enable-take-over-mode-in-coc-volar>

**Comment by Aaron34R** [comment]
> I don't think you need to do any special setup. Maybe there is something wrong with your project.
> 
> Create a project with `create-vite` or `create-vue` and try to see if it works correctly.
> 
> **create-vite**:
> 
> > https://github.com/vitejs/vite/tree/main/packages/create-vite
> 
> ```
> yarn create vite example-proj --template vue-ts
> ```
> 
> **create-vue**:
> 
> > https://github.com/vuejs/create-vue
> 
> ```
> npm init vue@3
> ```
> 
> In coc-volar, this can be enabled by executing the following `CocCommand`.
> 
> ```
> :CocCommand volar.initializeTakeOverMode
> ```
> 
> For more information, please check here. https://github.com/yaegassy/coc-volar#how-to-enable-take-over-mode-in-coc-volar

yes,you're right, thanks for helping
