### ISSUE TITLE
Custom diagnostics icon or use coc diagnostics icon

### ISSUE THREAD

**Issue by bigshans** [yaegassy/coc-volar#149]
Because I have defined the icon of diagnostics in coc but not work on here. I want the icons to be consistent with coc or I can customize the symbols.

**Comment by yaegassy** [comment]
I don't think there is any process on the coc-volar side to overwrite icons, sign, etc. Change the `diagnostic.XXXSign` setting.

- `diagnostic.hintSign`
- `diagnostic.infoSign`
- `diagnostic.warningSign`
- `diagnostic.errorSign`

Check `schema.json` in coc.nvim for details 

- <https://github.com/neoclide/coc.nvim/blob/master/data/schema.json>

If it is an icon for a completion item, please refer here.

- <https://github.com/neoclide/coc.nvim/blob/master/doc/coc.txt#L338-L371>

**Comment by bigshans** [comment]
Yes, finally I found it so I closed it. But thanks!
