### ISSUE TITLE
Getting [ts 2339] [E] Property '...' does not exist on type

### ISSUE THREAD

**Issue by 3ximus** [yaegassy/coc-volar#154]
I'm getting a `Property does not exist` error when accessing the data parameters inside a function. However this works fine in the application.
![image](https://user-images.githubusercontent.com/9083012/167321656-ed4ca5d4-fafc-404d-bba9-03e4bfdefb35.png)

Any ideas why this happens ?

**Comment by yaegassy** [comment]
Try using `defineComponent`.

```vue
<script lang="ts">
import { defineComponent } from "vue";

export default defineComponent({
  data() {
    // ...snip
  },
  methods: {
    // ...snip
  },
});
</script>
```

Or use the `<script setup lang="ts">`.

**Comment by yaegassy** [comment]
@3ximus If you want to use `export default { ... }` as it is, try adding a settings. Adding `vueCompilerOptions.experimentShamefullySupportOptionsApi` settings to `tsconfig.json` may solve the problem.

For projects created in `create-vue` (`npm init vue`), try adding settings to `tsconfig.app.json`.

---

**tsconfig.app.json**:

```jsonc
{
  "extends": "@vue/tsconfig/tsconfig.web.json",
  "include": ["env.d.ts", "src/**/*", "src/**/*.vue"],
  "exclude": ["src/**/__tests__/*"],
  "compilerOptions": {
    "composite": true,
    "baseUrl": ".",
    "paths": {
      "@/*": ["./src/*"]
    }
  },
  // ---- here ----
  "vueCompilerOptions": {
    "experimentalShamefullySupportOptionsApi": true
  }
}
```

**Comment by 3ximus** [comment]
Thank you for the quick reply, both solutions worked for me. Do you know how "shameful" this `experimentalShamefullySupportOptionsApi` is ?
Because I would rather use the Options API as it is in the documentation without the `defineComponent` function.

Cheers

**Comment by yaegassy** [comment]
This is not a configuration item added by `coc-volar` on its own, but by [upstream](https://github.com/johnsoncodehk/volar). If you are concerned about the name of the configuration, please submit an issue report upstream.

`export default {...}` is of course explained in the official vue documentation and is certainly nothing to be shamefull of. Of course, the same applies when using javascript instead of typescript.

In the current [volar](https://github.com/johnsoncodehk/volar), it is recommended to use `script setup` and `defineComponent` in `typescript` because it is less trouble.

**Comment by 3ximus** [comment]
I see, ok. Thank you for the reply and help.
Cheers :+1:

**Comment by yaegassy** [comment]
@3ximus It looks like `experimentalShamefullySupportOptionsApi` option will be enabled by default in the next upstream update. The diagnostic message appears as a warning, not a error. <https://github.com/johnsoncodehk/volar/commit/e361bdd72aefe4818c5a40e87d11b61672fdf6adA>

**Comment by 3ximus** [comment]
Oh that's great 👍
Thank you!

**Comment by yaegassy** [comment]
The latest version was released yesterday via upstream. coc-volar has also been updated. Try run `:CocUpdate` and update your extensions
