### ISSUE TITLE
Add Configuration for Packer 

### ISSUE THREAD

**Issue by HenftyKnight** [yaegassy/coc-volar#178]
Hey, it would be really great if you could, add configuration on how to install this using Packer.
I tried it and was just playing around with it.

```
cd ~/.config/nvim/lua
open packer_init.lua
add
->  use {'neoclide/coc.nvim', branch = 'release'}

":PackerInstall"

Once you have coc.nvim
:CocInstall @yaegassy/coc-volar
```
Awesome work!
Thanks

**Comment by yaegassy** [comment]
Thanks for the suggestion. 🙇

`coc.nvim` supports "Vim8" as well as "Neovim". `packer.nvim` is a plugin manager for "Neovim" only and does not work with "Vim8".

Even in the example of installing `coc.nvim` itself, `vim-plug` is employed.

Furthermore, as an additional note, I myself use `vim-plug` and do not use `packer.nvim`. Therefore, we may not be able to give you a correct answer if you report an issue related to `packer.nvim`.

There are many plugin managers for Vim/Neovim. The one using vim-plug is just one installation example. There are no plans to add examples of other package managers at this time. 🙇
