### ISSUE TITLE
[0.24.0] Volar not detecting template in script setup

### ISSUE THREAD

**Issue by sakarui** [yaegassy/coc-volar#201]
Recently, I upgraded from 0.23.3 to 0.24.
Suddenly, variables and imported components declared in <script setup> show the warning "[ts 6133] value is never read" for using in \<template>.

Variables are using in \<script setup> are correctly detecting.
However, variables which only used in \<template> show "value is never read" warnings.

I rollbacked coc-volar to 0.23.3, There is no problem, and problem has been solved

**Comment by yaegassy** [comment]
Hi,

The only change from "v0.23.3" to "v0.24.0" in `coc-volar` is an update to the language server. Therefore, it may be a problem associated with the update on the language server side.

I found a similar issue on the language server side. Check this issue. <https://github.com/johnsoncodehk/volar/issues/1694>

**Comment by Eusebius1920** [comment]
I am seeing the exact same issue in vscode extension:

- 0.39.5 works
- 0.40.0 does not work
- 0.40.1 does not work either

**Comment by yaegassy** [comment]
@sakarui @Eusebius1920 Hi, Can you please check if this issue is resolved in the latest version of `coc-volar`? The issue seems to be closed in upstream.

**Comment by sakarui** [comment]
@yaegassy Hello, I upgraded it to latest version, and all problems are solved. Thank you for your reply.
