### ISSUE TITLE
Does not work with ts files

### ISSUE THREAD

**Issue by emmanuelgeoffray** [yaegassy/coc-volar#204]
It works fine in vue files but in ts files I can't import Vue files.
For example, in `src/main.ts` :
![Screenshot from 2022-08-29 19-45-58](https://user-images.githubusercontent.com/808090/187265220-c66f5adf-24c0-467c-b940-f79a7fb477c6.png)

In [Vue doc](https://vuejs.org/guide/typescript/overview.html#ide-support), it is mentioned that we should install [TypeScript Vue Plugin](https://marketplace.visualstudio.com/items?itemName=Vue.vscode-typescript-vue-plugin).

I'm not sure if `coc-colar` also installs TypeScript Vue Plugin or if there is another `coc` implementation to install it.

**Comment by yaegassy** [comment]
Take Over Mode must be enabled. Please execute `:CocCommand volar.initializeTakeOverMode`.

See: https://github.com/yaegassy/coc-volar#how-to-enable-take-over-mode-in-coc-volar

**Comment by yaegassy** [comment]
If you want to use the "TypeScript Vue Plugin" instead of Take Over Mode, install `typescript-vue-plugin` in your project.

```
npm install typescript-vue-plugin
```

Then add the `plugins` configuration to tsconfig.

As an additional note, if you created the project with `create-vue`, you will need to add the configuration to `tsconfig.app.json`.

**tsconfig.app.json**:

```
{
  "extends": "@vue/tsconfig/tsconfig.web.json",
  "include": ["env.d.ts", "src/**/*", "src/**/*.vue"],
  "exclude": ["src/**/__tests__/*"],
  "compilerOptions": {
    "composite": true,
    "baseUrl": ".",
    "paths": {
      "@/*": ["./src/*"]
    },
    "plugins": [
      {
        "name": "typescript-vue-plugin"
      }
    ]
  }
}
```

**Comment by emmanuelgeoffray** [comment]
Thank you for your prompt reply !
It does work with enabling Take Over Mode.

Wouldn't be nice to mention enabling Take Over Mode in the "Recommended additional installation" ?
I think this is a pretty common scenario as every vue project as a `src/main.ts` file that will display TS errors without Take Over Mode.
