### ISSUE TITLE
`:CocCommand volar.initializeTakeOverMode` get an error!!

### ISSUE THREAD

**Issue by ancion** [yaegassy/coc-volar#214]
![image](https://user-images.githubusercontent.com/49437191/193170590-e8d34bd5-8165-4688-9bbb-505bec050fd9.png)

coc.nvim is latest version.
project package mainly used :  vite + vue3.2.37 + ts4.8.3

**Comment by yaegassy** [comment]
I cannot reproduce this in my environment. Are you using Vim or Neovim? Perhaps it is a problem with coc.nvim itself. Please file an issue report to coc.nvim itself.

**Comment by ancion** [comment]
thank&nbsp; you ！I&nbsp; use&nbsp; neovim 0.72&nbsp;&nbsp;



---Original---
From: ***@***.***&gt;
Date: Fri, Sep 30, 2022 09:43 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [yaegassy/coc-volar] `:CocCommand volar.initializeTakeOverMode`get an error!! (Issue #214)




 
I cannot reproduce this in my environment. Are you using Vim or Neovim? Perhaps it is a problem with coc.nvim itself. Please file an issue report to coc.nvim itself.
