### ISSUE TITLE
notarget No matching version found for @volar/vue-language-server@1.0.8

### ISSUE THREAD

**Issue by dreampasssser** [yaegassy/coc-volar#224]
My environment is Win11, I'm having some trouble.

Cannot install the plug-in & throw error "notarget No matching version found for @volar/vue-language-server@1.0.8".

 And the plug-in @yaegassy/coc-volar-tools cannot be installed too. It throw error "notarget No matching version found for @volar/preview@1.0.5".

**Comment by johnsoncodehk** [comment]
It seem a same issue with https://github.com/johnsoncodehk/volar/issues/2014.

**Comment by dreampasssser** [comment]
Thanks. I solved it. The source I used before was a mirror in CN and the latest version is 1.0.7. After I changed the source, it can be installed successfully.
