### ISSUE TITLE
It seems that ‘@’ completion is not supported？

### ISSUE THREAD

**Issue by BingCoke** [yaegassy/coc-volar#226]
![image](https://user-images.githubusercontent.com/81607010/200470228-c2362541-6666-4948-bfaf-716453d58ce5.png)

**Comment by yaegassy** [comment]
Reproduced. This could possibly be a bug in `coc.nvim`.

**Comment by BingCoke** [comment]
> Reproduced. This could possibly be a bug in `coc.nvim`.

i think so. coc may be not have detection of the @ prefix....similarly, coc-snippets has a snippet for vue's '@',but i need  enter shortcut key otherwise it  will not show.
before
![image](https://user-images.githubusercontent.com/81607010/200483342-5b9fee2d-e85f-4092-95d6-fce02d25adc6.png)

after enter shortcut key
![image](https://user-images.githubusercontent.com/81607010/200483414-58a261de-217f-404a-b975-de8590ec7fd9.png)

enter other prefix snippets work well
![image](https://user-images.githubusercontent.com/81607010/200483674-f8f48f09-de07-4dde-a207-5e779817c08d.png)

**Comment by yaegassy** [comment]
I have already reported the issue to coc.nvim itself, but if you have an older version of coc.nvim, @ will also appear in the completion fields correctly.

**Old version of coc.nvim screen shot**:

<img width="333" alt="old-coc-nvim" src="https://user-images.githubusercontent.com/188642/200485672-7ca8036c-7f38-4484-be55-d76daf2b2cd8.png">

**Comment by BingCoke** [comment]
OK,wait for the good news

**Comment by yaegassy** [comment]
There was a commit to fix it on the coc.nvim side. Please update coc.nvim.

I have already checked that this issue has been resolved in my environment

https://user-images.githubusercontent.com/188642/200710015-f28c9f8d-f8d4-4590-ade6-8670f2c6e405.mp4

**Comment by BingCoke** [comment]
> There was a commit to fix it on the coc.nvim side. Please update coc.nvim.
> 
> I have already checked that this issue has been resolved in my environment
> 
>  coc-volar-issue-226-resolved.mp4

fantastic！
