### ISSUE TITLE
How to how tsserver commands in takeover mode.

### ISSUE THREAD

**Issue by kalvenschraut** [yaegassy/coc-volar#229]
As of typescript 4.7 and [this commit of coc-tsserver](https://github.com/neoclide/coc-tsserver/pull/384) go to source definition was added. In takeover mode I am unsure how to run this command. 

`:CocCommand tsserver.goToSourceDefinition` works without takeover mode. Not sure if it is possible to run, or does volar need to implement a similar command?

**Comment by yaegassy** [comment]
volar's language server does not provide "Go to Source Definition" feature.

**Comment by kalvenschraut** [comment]
Okay, wasn't sure if the tsserver commands could still be used while in takeover mode or if volar had to implement a similar feature.
