### ISSUE TITLE
does coc-volar do any intellisense inside template and css block

### ISSUE THREAD

**Issue by laoshaw** [yaegassy/coc-volar#243]
or it only works inside script block in SFC?

**Comment by yaegassy** [comment]
Yes, of course it works with templates and styles blocks. `leafOfTree/vim-vue-plugin` is a plugin for vue syntax files, but it works with or without this plugin.

There may be some problem with your environment. Try it with a minimal vue project.

**Prepare Project**:

```
mkdir /tmp
cd /tmp
npm init vue check-proj
...
cd check-proj
npm i

```

**Open the vue file in Vim/Neovim**:

```
nvim src/App.vue
```

**Execute the following command**:

```
:CocCommand volar.initializeTakeOverMode
```

**Comment by yaegassy** [comment]
If the `workspacefolders` is not resolved correctly in coc.nvim, as it may be, you may have a problem.

Please check this section of the README.

- <https://github.com/yaegassy/coc-volar#workspacefolders>

**Comment by yaegassy** [comment]
In my environment, I checked a case where `workspaceFolder` did not resolve correctly. I knew that case had the same symptoms as yours.

We have added some additional settings on the extension side. Please update coc-volar.
