### ISSUE TITLE
not support CSS hints

### ISSUE THREAD

**Issue by xd-shadow** [yaegassy/coc-volar#25]
projects built with vite-plugin-SSR do not support CSS hints

**Comment by xd-shadow** [comment]
![image](https://user-images.githubusercontent.com/35983043/130193478-b58a4301-0c04-463c-8b43-d2b0c5108bd9.png)

**Comment by johnsoncodehk** [comment]
Do you have tsconfig? See https://github.com/johnsoncodehk/volar#using.

**Comment by yaegassy** [comment]
Thanks!!!, @johnsoncodehk

@xd-shadow Is the problem solved? Check the README for [johnsoncodehk/volar](https://github.com/johnsoncodehk/volar#note)

> tsconfig.json / jsconfig.json is required for now.
>
> Also required "strict": true and "moduleResolution": "node".

I tried vite-plugin-ssr in my environment and it worked fine.

In the case of `vue` ("Vue + JavaScript"), you need to create `tsconfig.json` or `jsconfig.json`.

**Comment by yaegassy** [comment]
@xd-shadow volar v0.27.7 has been released.

**Changelog**:

> - feat: support for non-tsconfig project ([#349](https://github.com/johnsoncodehk/volar/issues/349))

Update the volar extention in VSCode and try it,

For coc-volar, please run `:CocUpdate` to update the coc extension.

**Comment by xd-shadow** [comment]
This issue has been resolved，thanks.
