### ISSUE TITLE
deprecated dependency

### ISSUE THREAD

**Issue by timsu92** [yaegassy/coc-volar#250]
I just updated this plugin and see that `sourcemap-codec@1.4.8` is deprecated and npm suggests `@jridgewell/sourcemap-codec` instead

**Comment by yaegassy** [comment]
Hi, Thanks for the report. It's a warning (WARN) on the dependency side of the package you are using. It is a package related to the vue core.

I can reproduce it just by installing vue itself directly.

```
$ npm i vue
npm WARN deprecated sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead

added 21 packages, and audited 22 packages in 2s

1 package is looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```

If necessary, please report to the vue core side.
