### ISSUE TITLE
file path completion when resolve alias with '@'

### ISSUE THREAD

**Issue by strongWei** [yaegassy/coc-volar#260]
i want nvim to  hint '@/asset' , how should i do
![2023-03-15_19-19](https://user-images.githubusercontent.com/11831357/225294883-85ab998e-8a4b-4bdd-94cc-6ba240f34198.png)

my tsconfig.json is below:
![image](https://user-images.githubusercontent.com/11831357/225295511-73ba12e4-c3e8-4ea0-943b-72d73819ad2c.png)

**Comment by yaegassy** [comment]
It is working correctly in my environment. I cannot reproduce your problem.

https://user-images.githubusercontent.com/188642/225299635-54e49c64-365a-47fe-a594-5bb2be477b16.mp4

**Comment by strongWei** [comment]
i only installed extension: coc-vetur, coc-volar, coc-tsserver, and not enable `takeover` mode, my `CocLocalConfig` is:
```json
{
    "vetur.enable": false,
    "tsserver.enable": false
}
```
when i enable `tsserver`, it appears to work:
![image](https://user-images.githubusercontent.com/11831357/225518571-efa24f0a-91f4-49f1-af72-ec9ffd4a0779.png)
  
 however, it still has error: 
![image](https://user-images.githubusercontent.com/11831357/225517374-d459074d-64bd-4f29-8472-c26a8a94a932.png)

the `components` directory is not only contain `icons`, i think the error `cannot find module '@/ExampleApp.vue'` is possibly the problem, but i don't know how to fixed it, that is why i disable `tsserver` .
can you help me?

**Comment by strongWei** [comment]
when i turn on the `take over mode`, the problem has be fixed
