### ISSUE TITLE
Cannot jump to component without `.vue` file extension

### ISSUE THREAD

**Issue by gsuxlzt** [yaegassy/coc-volar#289]
Hi. I might just be missing some configs, but I cannot jump to a different component when the path of that component does not include the `.vue` file extension. Jumping to `.js` files work fine even if they're missing the extension, but for some reason, Vue components need to have a `.vue` in the import statement for the JumpDefinition to work. Any ideas or workarounds?

**Comment by yaegassy** [comment]
It may be possible to use the `moduleSuffixes` setting in tsconfig.json to make the JumpDefinition, but I don't know the relevant correct way to set it up, etc. https://www.typescriptlang.org/tsconfig#moduleSuffixes

Please check the documentation of tsconfig.json to see if there are any settings available that can fulfill your desired behavior.
