### ISSUE TITLE
Auto release new version with `@volar/server`

### ISSUE THREAD

**Issue by johnsoncodehk** [yaegassy/coc-volar#31]
When volar updated, coc-volar usually does not need to change the code. Are you interested in using GitHub Action to automatically release coc-volar when `@volar/server` released a new version? (If tsc compile pass)

**Comment by yaegassy** [comment]
@johnsoncodehk Thanks for the great advice. 🙇

I enjoy updating volar at the moment, so I don't need GitHub Action or other automatic release.😇

**Comment by johnsoncodehk** [comment]
I am worried that this is annoying for you, because it is updated frequently currently. Nice to hear!
