### ISSUE TITLE
Diagnostic issue (not showing)

### ISSUE THREAD

**Issue by samz-paypay** [yaegassy/coc-volar#316]
Diagnostic info is not showing up, probably after I did an update? I don't remember exactly.
I see [a similar issue ](https://github.com/yaegassy/coc-volar/issues/259)earlier.

Not showing in vue file:
<img width="601" alt="image" src="https://github.com/yaegassy/coc-volar/assets/133731586/5adc1453-8bda-4142-8c63-b64472fd9b5a">

Shows in normal ts file:
<img width="496" alt="image" src="https://github.com/yaegassy/coc-volar/assets/133731586/c2139898-c114-4441-afd9-3c3b49abe9f3">

I use takeover mode:
```json
  "volar.takeOverMode.enabled": true,
  "tsserver.enable": false
```
Diagnostic will show if I change `tsserver.enable` to true, but I don't think that's what I should do.

Thanks in advance!

**Comment by yaegassy** [comment]
Hi, @samz-paypay. I created a vue project and tried it out.

```
npm create vue@latest check-proj
```

It seems to work fine in my environment.

https://github.com/yaegassy/coc-volar/assets/188642/e2d49da3-6035-4826-9b20-e0021c9c898f

**Comment by samz-paypay** [comment]
Is it in takeover mode?
It also works on my side if it's NOT in takeover mode.

**Comment by yaegassy** [comment]
Yes, I have the demo posted above in takeover mode.

**Comment by samz-paypay** [comment]
Thank you very much for your time!
It turns out some other developer changed our tsconfig in the repo, and I upgraded the plugin at about the same time...
Thanks again and sorry for the false accusation 😭 

So the change is
```json
"include": ["./**/*"]
```
was added. This seems to include everything, not sure why it's causing issues.
