### ISSUE TITLE
Disable autocompletion source

### ISSUE THREAD

**Issue by bpolly** [yaegassy/coc-volar#319]
Is there a way to disable autocompletion suggestions from the Volar LS? I'm getting lots of noise from this plugin/vue-semantic-server via the autocomplete menu - is there a way to disable this programmatically? My current workaround is to call `:CocList sources` and toggle it off, but it resets each time Vim is opened.

<img width="605" alt="image" src="https://github.com/yaegassy/coc-volar/assets/2245006/017cd278-b9f6-476d-9378-7701a3716f02">

The `tsserver` CoC plugin has configurations like
```
typescript.suggest.enabled
javascript.suggest.enabled
```
but I'm not seeing anything similar for Volar in the docs.

**Comment by yaegassy** [comment]
Add the setting `volar.disableCompletion`, update coc-volar to the latest version and set it to true in `coc-settings.json`.

**coc-settings.json**:

```jsonc
{
  "volar.disableCompletion": true
}
```

**Comment by bpolly** [comment]
Worked perfectly 🎉 

Thanks so much!
