### ISSUE TITLE
Property 'loading' does not exist on type '{}'.

### ISSUE THREAD

**Issue by seriiserii825** [yaegassy/coc-volar#326]
Hi, thanks for plugin. 
I am using vue3 composition api
I tested 2 methods, Takeover Mode, and typescript-vue-plugin, but for both have this error. 

For example, for this component, i have error from header:
```
    <div class="container" style="padding: 3.2rem 0;" v-if="loading">
      <LoadingComponent/>
    </div>

```
And also this error exists and for other Components properties or emits.

I founded in google a lot of reasons, but no one don't work. 
Like, to create a file ** vue-file-import.d.ts** with this ext
```
declare module "*.vue" {
  import Vue from "vue";
  export default Vue;
}

```

Or in main.ts to add
```
    app.config.globalProperties.appName = 'vue3'

```

Thanks in advance.

**Comment by yaegassy** [comment]
I apologize for the late reply. For questions about the behavior of Vue itself or the language server itself, it would be better to ask upstream vuejs/language-tools or the Vue community for a more accurate answer.

I will close this issue.
