### ISSUE TITLE
`vue.autoInsert.bracketSpacing` doesn't seem to work. And syntax highlighting is abnormal.

### ISSUE THREAD

**Issue by dreampasssser** [yaegassy/coc-volar#328]
1. `vue.autoInsert.bracketSpacing` doesn't seem to work.

2. Syntax highlighting is abnormal when scrolling down in a SFC that has a long `script` part.

**Comment by yaegassy** [comment]
Hi, @dreampasssser 

> 1. vue.autoInsert.bracketSpacing doesn't seem to work.

I've implemented `vue.autoInsert.bracketSpacing`.

To enable this feature, you need to have a plugin installed that automatically inserts `}` when you type `{`, such as `jiangmiao/auto-pairs`. By the way, VS Code has this feature built-in by default.

**DEMO(mp4)**:

https://github.com/yaegassy/coc-volar/assets/188642/126972de-c6fa-42b9-9082-c4293390d844

---

> 2. Syntax highlighting is abnormal when scrolling down in a SFC that has a long script part.

Syntax highlighting is out of the scope of coc-volar. Please contact your syntax highlighting plugin for support.

By the way, I use [nvim-treesitter](https://github.com/nvim-treesitter/nvim-treesitter) for Neovim and [leafOfTree/vim-vue-plugin](https://github.com/leafOfTree/vim-vue-plugin) for Vim9.

Unfortunately, [posva/vim-vue](https://github.com/posva/vim-vue) is no longer maintained and is therefore not recommended.

**Comment by dreampasssser** [comment]
@yaegassy 

I had installed `jiangmiao/auto-pairs` , but `vue.autoInsert.bracketSpacing` still didn't work.

My platform is 'win11, windows terminal, powershell7.4.1, vim9.1'.

**Comment by yaegassy** [comment]
@dreampasssser I have made some adjustments. Please update coc-volar and try again. https://github.com/yaegassy/coc-volar/commit/cc8425228de231959491fb05f6ff8f7949e9bb77

**Comment by dreampasssser** [comment]
@yaegassy It is OK now, thank you.
