### ISSUE TITLE
Doesn't work properly when updating to the latest version (0.35.5)

### ISSUE THREAD

**Issue by LemonAppleMo** [yaegassy/coc-volar#337]
Node Version: v20.11.0
Npm Version: 10.2.4
coc-volar Version: 0.35.5

The error is：

<img width="897" alt="image" src="https://github.com/yaegassy/coc-volar/assets/32638462/4f722f01-df72-441f-98fe-416b05f067fa">

<img width="1224" alt="image" src="https://github.com/yaegassy/coc-volar/assets/32638462/e0ed96db-a55a-4ed8-b17b-76f1f904ac0b">

---

Opening the project in vscode did not reveal the problem:

<img width="581" alt="image" src="https://github.com/yaegassy/coc-volar/assets/32638462/56f8ab1a-648a-49a3-b368-2b209ea66301">

**Comment by LemonAppleMo** [comment]
把coc-volar版本回退到0.35.4可以正常加载

<img width="638" alt="image" src="https://github.com/yaegassy/coc-volar/assets/32638462/ed12ee53-52b0-49de-8a3b-3f07a88c86da">

**Comment by yaegassy** [comment]
Hi, @LemonAppleMo, Sorry for the late reply.

I was able to reproduce the issue in my environment with coc-volar `v0.35.5` installed via npm.

I have upgraded the version of the language server and published `v0.35.6` to npm. I believe this issue is resolved in `v0.35.6`, so please give it a try.

**Comment by LemonAppleMo** [comment]
Thank you for your reply, there are no problems in the latest version, thank you very much~ 😊😊
