### ISSUE TITLE
Typescript errors in non typescript vue file

### ISSUE THREAD

**Issue by humpangle** [yaegassy/coc-volar#34]
Thanks for this project - it works in great for typescript project. I have a non typescript `.vue` file and now that I upgraded to coc-volar 0.5.10 I started getting typescript errors such as 

```
[ts 2322] [E] Type '() => void' is not assignable to type 'never'.
```

mostly in callback props. How can I resolve this? Thanks.

**Comment by yaegassy** [comment]
Does this problem also occur with VSCode's volar extension?

If possible, could you please provide the smallest code sample you can reproduce?

---

If downgrading the version of coc-volar temporarily solves your problem, please give it a try.

```
:CocUninstall @yaegassy/coc-volar
:CocInstall @yaegassy/coc-volar@0.5.9
```

**Comment by humpangle** [comment]
Thanks for the response. Downgrading to 0.5.9 did make the errors go away, but then there is no longer intellisense. You can take a look  here `https://github.com/humpangle/non-typescript-vue-coc-volar/blob/36d29889a43d7406a803929854f75a794fda93b3/src/components/HelloWorld.vue#L2`

You will get errors for both the `sayHi` callback and the `msg` prop.

Below are my `coc-volar` and vue related settings:

```
  "volar.codeLens.references": false,
  "volar.codeLens.pugTools": false,
  "volar.codeLens.scriptSetupTools": false,
  "volar.formatting.enable": false,
  "prettier.disableLanguages": [],
  "emmet.includeLanguages": {
    "vue-html": "html",
  }
```

**Comment by johnsoncodehk** [comment]
Hi @humpangle, please install `@vue/runtime-dom` for vue 2 project. See https://github.com/johnsoncodehk/volar#using.

**Comment by yaegassy** [comment]
By installing `@vue/runtime-dom`, the error was resolved in my environment. (coc-volar `v0.5.10`)

@humpangle Did you solve the problem?

As a side note, coc-volar v0.5.9 (volar v0.27.6) or earlier required tsconfig.json or jsconfig.json in the project.

**Comment by humpangle** [comment]
Thanks @johnsoncodehk and @yaegassy  . I have installed `@vue/runtime-dom` as suggested and that made the errors go away.

But I have found the problem is with `@vue/composition-api`.  If you look at the repo `https://github.com/humpangle/non-typescript-vue-coc-volar` in commit [624c5f5](https://github.com/humpangle/non-typescript-vue-coc-volar/commit/624c5f56abecb53164ba90745a902e6cd6fb4b5c) where I introduced `@vue/composition-api`  here `https://github.com/humpangle/non-typescript-vue-coc-volar/blob/624c5f56abecb53164ba90745a902e6cd6fb4b5c/src/components/Some.vue#L8`, then I started getting the same callback error as in my actual project. 

Here is the location of the error `https://github.com/humpangle/non-typescript-vue-coc-volar/blob/624c5f56abecb53164ba90745a902e6cd6fb4b5c/src/components/HelloWorld.vue#L2`.

The error message:

```
[ts 2322] [E] Type 'any' is not assignable to type 'never'.
```

**Comment by johnsoncodehk** [comment]
Please forward `@vue/composition-api` typing issue to `@vue/composition-api` repo.

**Comment by humpangle** [comment]
Thanks @johnsoncodehk. I will do just that right away.

But should I be getting type issues in a non TS project? Apologies if I should have found the answer some where.

**Comment by humpangle** [comment]
I have raised the issue with `@vue/composition-api`.  @yaegassy , would you like me to close this issue?

**Comment by johnsoncodehk** [comment]
> Thanks @johnsoncodehk. I will do just that right away.
> 
> But should I be getting type issues in a non TS project? Apologies if I should have found the answer some where.

Maybe follow https://github.com/johnsoncodehk/volar/issues/411.
