### ISSUE TITLE
Autoimport only works for "script setup" components

### ISSUE THREAD

**Issue by guihig** [yaegassy/coc-volar#37]
Hi,

The component auto import feature only works if the imported component is defined by "script setup",

Here is an print when i try to import a non script setup component into one.

![Screenshot from 2021-08-25 12-13-12](https://user-images.githubusercontent.com/6731688/130817655-783ac112-12fa-4c0d-acc2-f1d383f0f26b.png)

Is there any configuration that i'm missing?

Thanks in advance

**Comment by johnsoncodehk** [comment]
Insufficient information to check the problem, please try to make and provide a reproduce by https://github.com/johnsoncodehk/volar-starter.

**Comment by yaegassy** [comment]
@guihig 

"v0.27.8" version of volar has been released. Your problem may have been solved. Please give it a try.

coc-volar has already been updated to use 0.27.8.

The issue will be closed as this is not a coc-volar specific issue.

**Comment by guihig** [comment]
Yeah, it was fixed after the new update.

Thanks again for the good work.
