### ISSUE TITLE
Language Client is not ready yet

### ISSUE THREAD

**Issue by guihig** [yaegassy/coc-volar#59]
Hi, i'm having some trouble to get coc-volar running after the update 0.5.30

It just occur when i type anything inside any vue file.

![Screenshot from 2021-09-15 16-09-16](https://user-images.githubusercontent.com/6731688/133494959-694d6457-0e99-46a9-bc94-036d4c0df0c6.png)

Is there any config im missing?

**Comment by guihig** [comment]
In addition to this error, when its initialized throws this message:

![Screenshot from 2021-09-15 16-45-56](https://user-images.githubusercontent.com/6731688/133499489-6bfc2907-5a9c-4b58-ba77-9aed62713cb6.png)

**Comment by yaegassy** [comment]
@guihig Hi, Thanks for the issue report. 

I can't reproduce the error in my environment.

1. Can you please share the output of `:CocCommand volar.doctor`?
2. What kind of input will cause this error?
3. I've just released coc-volar `v0.5.31` (Sync VSCode's volar v0.27.21). Do you get the same error after updating to `v0.5.31` with `:CocUpdate`?

**Comment by guihig** [comment]
Hello, i've just updated and the error is gone, thank you
