### ISSUE TITLE
Cannot read property 'start' of undefined

### ISSUE THREAD

**Issue by Lilja** [yaegassy/coc-volar#68]
Hey! I tried to install this and test this using vue-vite: I get really weird errors:

`:CocInfo`
![image](https://user-images.githubusercontent.com/6134511/135619771-7b92b85a-9ea2-4207-992e-c97dc41100d0.png)

![image](https://user-images.githubusercontent.com/6134511/135619848-e87f9f8b-4c79-4bfd-855e-fec9c01be368.png)

`:messages`
![image](https://user-images.githubusercontent.com/6134511/135619893-586cd04e-1af7-4f29-a9e2-67ca2d551b0f.png)

**Comment by yaegassy** [comment]
I tried it in my environment, but I could not reproduce the problem.

What is the output result of `:CocCommand volar.doctor`?

Your `coc.nvim` seems to be very very old. It may be the version where the bug exists. First, try updating coc.nvim to the latest version and then see if the same problem occurs.

**Comment by Lilja** [comment]
Did not realize I had an old coc.nvim version. 7 months is "very very old"? 🤔 

Updated coc.nvim and seems to have resolved itself

**Comment by yaegassy** [comment]
> 7 months is "very very old"? 🤔

I'm sorry if I made you feel uncomfortable. 🙇

I update Neovim, Vim8, and various plugins and extensions to the latest versions every day.

Anyway, I am relieved that your problem has been solved.

**Comment by Lilja** [comment]
Don't worry, I wasn't offended. It's probably a good idea to update things more often than 7 months. That fault lies completely with me 😄
