### ISSUE TITLE
If "takeOverMode" is enabled, "tsserver" needs to be stopped (duplicate completion, etc...)

### ISSUE THREAD

**Issue by yaegassy** [yaegassy/coc-volar#83]
> "volar.takeOverMode.enabled": true

**coc-volar**:

https://user-images.githubusercontent.com/188642/137430356-8e09c330-60c7-494b-afc1-59569ef97526.mp4

**VSCode's volar extension (upstream)**:

> Same

<img width="1170" alt="volar-upstream-issue211015" src="https://user-images.githubusercontent.com/188642/137430392-62fcc47b-05f0-416f-885d-d3a2f93a4563.png">

**Comment by yaegassy** [comment]
I was able to stop it by deactivate() only when takeOverMode is enabled.

However, we will need to consider a number of things, including the most recent changes to activationEvents.

```typescript
// ...snip
    const takeOverMode = takeOverModeEnabled();
    if (takeOverMode && ['javascript', 'typescript', 'javascriptreact', 'typescriptreact'].includes(currentlangId)) {
      doActivate(context);
      const tsserver = extensions.all.find((e) => e.id === 'coc-tsserver');
      if (tsserver?.isActive) {
        try {
          // @ts-ignore
          await tsserver.deactivate();
        } catch {
          // noop
        }
      }
    }
// ...snip
```

**Comment by johnsoncodehk** [comment]
Can user manual disable `coc-tsserver`? If yes, I think coc-volar do not need disable `coc-tsserver` automatic, just tell user config `"volar.takeOverMode.enabled": true` with disable `coc-tsserver` on readme is good enough.

**Comment by yaegassy** [comment]
@johnsoncodehk Thank you for confirming my issue.

For now, I decided to prepare command in coc-volar. https://github.com/yaegassy/coc-volar/pull/84
