### ISSUE TITLE
Why is it automatically imported from '@vue/reactivity' instead of 'vue'  

### ISSUE THREAD

**Issue by xd-shadow** [yaegassy/coc-volar#90]
![image](https://user-images.githubusercontent.com/35983043/139783474-faff6d9d-b02d-477a-8454-f37308e8981a.png)

**Comment by yaegassy** [comment]
Your screenshot seems to be "VSCode's volar extension", not `coc-volar`. But of course, coc-volar behaves in the same way.

It seems to be a specification of the volar language server.

If you are concerned about this behavior, you may want to report an issue to upsteam. 
https://github.com/johnsoncodehk/volar/issues

As a side note, Code Action seems to be an import statement for `'vue'`.

**Code Action**:

<img width="472" alt="vscode-volar-import-action" src="https://user-images.githubusercontent.com/188642/139785805-afce4845-7b97-4d75-adda-6ed9231086a7.png">

**Comment by johnsoncodehk** [comment]
This is upstream TS issue, see https://github.com/johnsoncodehk/volar/issues/532.

**Comment by yaegassy** [comment]
Hi, I think this issue has been resolved in typescript `v4.5.2`.

**DEMO(mp4)**:

https://user-images.githubusercontent.com/188642/143405804-f7af79e7-1d85-4e45-b8d6-db7e97c1d23d.mp4

**REF**:

- <https://github.com/johnsoncodehk/volar/issues/102#issuecomment-978895948>

Close this issue.
